const KEY="ofa3data",PASS="ofa3pass",N=100;
let D=JSON.parse(localStorage.getItem(KEY)||'{"profiles":[],"messages":[]}'),selected="",page=0,fpage=0;
const $=s=>document.querySelector(s),save=()=>localStorage.setItem(KEY,JSON.stringify(D)),id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2),esc=s=>String(s||"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
$("#open").onclick=()=>{let p=$("#pass").value.trim(),o=localStorage.getItem(PASS);if(!p)return $("#err").textContent="Enter a password.";if(!o)localStorage.setItem(PASS,p);else if(o!==p)return $("#err").textContent="Wrong password.";$("#lock").hidden=true;$("#app").hidden=false;renderHome();fill()};
document.querySelectorAll("aside [data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll("main section").forEach(x=>x.hidden=true);$("#"+b.dataset.page).hidden=false;if(b.dataset.page==="chat")renderChat(true);if(b.dataset.page==="fav")renderFav(true);if(b.dataset.page==="flash")flash();if(b.dataset.page==="stats")renderStats();});
$("#add").onclick=()=>{let n=prompt("Person name:");if(n){D.profiles.push({id:id(),name:n,sources:[]});save();fill();renderHome()}};
$("#import").onclick=()=>{if(!D.profiles.length)return alert("First add a person.");let n=prompt(D.profiles.map((p,i)=>`${i+1}. ${p.name}`).join("\n")+"\nChoose number:"),p=D.profiles[(+n)-1];if(!p)return;let s=prompt("Source label (Old Number / New Number):","WhatsApp Chat");$("#txt").dataset.p=p.id;$("#txt").dataset.s=s||"WhatsApp Chat";$("#txt").click()};
function nd(s){let m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);return m?`${m[3].length===2?"20"+m[3]:m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""}
$("#txt").onchange=e=>{let f=e.target.files[0],r=new FileReader();if(!f)return;r.onload=()=>{let p=e.target.dataset.p,s=e.target.dataset.s,pro=D.profiles.find(x=>x.id===p);if(!pro.sources.includes(s))pro.sources.push(s);let seen=new Set(D.messages.filter(x=>x.pid===p&&x.src===s).map(x=>x.date+"|"+x.time+"|"+x.sender+"|"+x.text)),last=null,a=0;for(let l of r.result.split(/\r?\n/)){let m=l.match(/^(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4}),?\s+(\d{1,2}:\d{2}(?:\s?[AP]M)?)\s+-\s+([^:]+):\s?(.*)$/i)||l.match(/^\[(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4}),?\s+(\d{1,2}:\d{2}(?:\s?[AP]M)?)\]\s+([^:]+):\s?(.*)$/i);if(m){let x={id:id(),pid:p,src:s,date:nd(m[1]),time:m[2],sender:m[3].trim(),text:m[4],fav:false},k=x.date+"|"+x.time+"|"+x.sender+"|"+x.text;if(!seen.has(k)){D.messages.push(x);seen.add(k);last=x;a++}else last=null}else if(last&&l.trim())last.text+="\n"+l}D.messages.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));save();fill();renderHome();alert(a+" new messages imported. Duplicates skipped.")};r.readAsText(f);e.target.value=""};
function fill(){let p=$("#person"),s=$("#source"),pv=p.value||"all",sv=s.value||"all";p.innerHTML='<option value="all">All People</option>'+D.profiles.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");p.value=[...p.options].some(x=>x.value===pv)?pv:"all";let ps=p.value==="all"?D.profiles:D.profiles.filter(x=>x.id===p.value);s.innerHTML='<option value="all">All Numbers / Sources</option>'+[...new Set(ps.flatMap(x=>x.sources))].map(x=>`<option>${esc(x)}</option>`).join("");if([...s.options].some(x=>x.value===sv))s.value=sv}
function filtered(){let p=$("#person").value,s=$("#source").value,q=$("#search").value.toLowerCase();return D.messages.filter(m=>(p==="all"||m.pid===p)&&(s==="all"||m.src===s)&&(!selected||m.date===selected)&&(!q||(`${m.sender} ${m.text} ${m.src}`).toLowerCase().includes(q)))}
function renderChat(reset){if(reset)page=0;fill();let a=filtered(),start=page*N,end=Math.min(start+N,a.length),slice=a.slice(start,end),prev=start?a[start-1].date:"",h="";$("#date").value=selected;$("#day").textContent=selected||"All Memories";$("#count").textContent=a.length.toLocaleString()+" matching messages";for(let m of slice){if(m.date!==prev){h+=`<div class="date">📅 ${m.date}</div>`;prev=m.date}h+=`<div class="msg"><button class="star" data-id="${m.id}">${m.fav?"⭐":"☆"}</button><div class="meta">${esc(m.sender)} • ${esc(m.time)} • 📱 ${esc(m.src)}</div>${esc(m.text).replace(/\n/g,"<br>")}</div>`}if(reset)$("#list").innerHTML=h||'<div class="empty">No matching memories 💌</div>';else $("#list").insertAdjacentHTML("beforeend",h);document.querySelectorAll("#list [data-id]").forEach(b=>b.onclick=()=>toggle(b.dataset.id));$("#more").hidden=end>=a.length}
function toggle(i){let m=D.messages.find(x=>x.id===i);m.fav=!m.fav;save();renderChat(true)}
$("#more").onclick=()=>{page++;renderChat(false)};["person","source"].forEach(x=>$("#"+x).onchange=()=>renderChat(true));$("#date").onchange=e=>{selected=e.target.value;renderChat(true)};let timer;$("#search").oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>renderChat(true),180)};$("#reset").onclick=()=>{selected="";$("#date").value="";$("#search").value="";$("#person").value="all";fill();$("#source").value="all";renderChat(true)};
function move(n){if(!selected){let d=[...new Set(D.messages.map(x=>x.date))].sort();selected=d[n>0?0:d.length-1]||""}else{let d=new Date(selected+"T12:00:00");d.setDate(d.getDate()+n);selected=d.toISOString().slice(0,10)}renderChat(true)}$("#prev").onclick=()=>move(-1);$("#next").onclick=()=>move(1);
function renderFav(reset){if(reset)fpage=0;let a=D.messages.filter(x=>x.fav),st=fpage*N,en=Math.min(st+N,a.length),h=a.slice(st,en).map(m=>`<div class="msg"><button class="star" data-f="${m.id}">⭐</button><div class="meta">${m.date} • ${esc(m.sender)} • 📱 ${esc(m.src)}</div>${esc(m.text)}</div>`).join("");if(reset)$("#favlist").innerHTML=h||'<div class="empty">No favorites yet</div>';else $("#favlist").insertAdjacentHTML("beforeend",h);document.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{D.messages.find(x=>x.id===b.dataset.f).fav=false;save();renderFav(true)});$("#favmore").hidden=en>=a.length}$("#favmore").onclick=()=>{fpage++;renderFav(false)};
function flash(){if(!D.messages.length){$("#flashtitle").textContent="Import a chat first ❤️";return}let ds=[...new Set(D.messages.map(x=>x.date))],d=ds[Math.floor(Math.random()*ds.length)],a=D.messages.filter(x=>x.date===d).slice(0,25);$("#flashtitle").textContent="A memory from "+d+" ❤️";$("#flashlist").innerHTML=a.map(m=>`<div class="msg"><div class="meta">${esc(m.sender)} • ${m.time} • ${esc(m.src)}</div>${esc(m.text)}</div>`).join("")}$("#flashbtn").onclick=flash;
function card(){let days=new Set(D.messages.map(x=>x.date)).size,src=new Set(D.messages.map(x=>x.src)).size,f=D.messages.filter(x=>x.fav).length;return [["💬 Total Messages",D.messages.length],["📅 Memory Days",days],["📱 Sources",src],["⭐ Favorites",f]].map(x=>`<div class="card">${x[0]}<div class="num">${x[1].toLocaleString()}</div></div>`).join("")}
function renderHome(){$("#cards").innerHTML=card();$("#profiles").innerHTML=D.profiles.map(p=>`<div class="row">❤️ ${esc(p.name)}<b>${D.messages.filter(x=>x.pid===p.id).length.toLocaleString()} messages</b></div>`).join("")||"No profile yet."}function renderStats(){$("#statcards").innerHTML=card()}
$("#export").onclick=()=>{let b=new Blob([JSON.stringify(D)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="Our-Forever-Archive-Backup.json";a.click()};$("#restore").onclick=()=>$("#json").click();$("#json").onchange=e=>{let r=new FileReader(),f=e.target.files[0];if(!f)return;r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.profiles||!x.messages)throw 0;D=x;save();fill();renderHome();alert("Backup restored ❤️")}catch{alert("Invalid backup")}};r.readAsText(f)};$("#clear").onclick=()=>{if(confirm("Delete all local data?")){D={profiles:[],messages:[]};save();fill();renderHome()}};