const $=s=>document.querySelector(s); const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let data=store.get('studyverse_v1',{xp:0,totalMinutes:0,tasks:[{text:'Plan today’s study session',done:false},{text:'Complete one focused lesson',done:false}],subjects:[{name:'Physics',progress:25},{name:'Chemistry',progress:18},{name:'Biology',progress:35},{name:'Higher Math',progress:15}],examDate:''});
function save(){store.set('studyverse_v1',data);render();}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function level(){return Math.floor(data.xp/100)+1}function updateStreak(){const d=new Date().toDateString(),x=store.get('studyverse_streak',{});if(x.last!==d){const y=new Date(Date.now()-864e5).toDateString();x.count=x.last===y?(x.count||0)+1:1;x.last=d;store.set('studyverse_streak',x)}return x.count||0}
function render(){const xp=data.xp%100;$('#levelText').textContent='Level '+level();$('#xpText').textContent=xp+' / 100 XP';$('#xpBar').style.width=xp+'%';$('#streak').textContent=store.get('studyverse_streak',{}).count||0;$('#totalHours').textContent=(data.totalMinutes/60).toFixed(data.totalMinutes>=60?1:0)+'h';$('#completedCount').textContent=data.tasks.filter(x=>x.done).length;$('#taskList').innerHTML=data.tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask(${i})"><span>${esc(t.text)}</span><button class="delete" onclick="deleteTask(${i})">×</button></div>`).join('');$('#subjects').innerHTML=data.subjects.map((s,i)=>`<div class="subject-row"><span>${esc(s.name)}</span><input type="range" min="0" max="100" value="${s.progress}" oninput="changeSubject(${i},this.value)"><b>${s.progress}%</b></div>`).join('');let sorted=[...data.subjects].sort((a,b)=>a.progress-b.progress);$('#weaknessList').innerHTML=sorted.map(s=>{let c=s.progress<35?'weak-badge':s.progress<70?'medium':'strong',t=s.progress<35?'Weak':s.progress<70?'Medium':'Strong';return `<div class="weak"><span>${esc(s.name)}</span><span class="badge ${c}">${t} · ${s.progress}%</span></div>`}).join('');const a=[['🌱','First Quest','Complete 1 task',data.tasks.some(x=>x.done)],['🔥','On Fire','Build a 3-day streak',(store.get('studyverse_streak',{}).count||0)>=3],['⚡','Focus Master','Focus for 1 hour',data.totalMinutes>=60],['🏆','Level Up','Reach Level 2',level()>=2]];$('#achievements').innerHTML=a.map(x=>`<div class="achievement ${x[3]?'unlocked':''}"><div>${x[0]}</div><b>${x[1]}</b><span>${x[2]}</span></div>`).join('');$('#examDate').value=data.examDate||'';updateCountdown();}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}window.toggleTask=i=>{let was=data.tasks[i].done;data.tasks[i].done=!was;if(!was){data.xp+=10;updateStreak();toast('+10 XP — Quest completed!')}save()};window.deleteTask=i=>{data.tasks.splice(i,1);save()};window.changeSubject=(i,v)=>{data.subjects[i].progress=+v;save()};
$('#addTaskBtn').onclick=()=>$('#taskForm').classList.toggle('hidden');$('#taskForm').onsubmit=e=>{e.preventDefault();data.tasks.push({text:$('#taskInput').value.trim(),done:false});$('#taskInput').value='';$('#taskForm').classList.add('hidden');save();toast('New quest added!')};$('#subjectForm').onsubmit=e=>{e.preventDefault();let n=$('#subjectName').value.trim();if(n){data.subjects.push({name:n,progress:0});$('#subjectName').value='';save()}};$('#examDate').onchange=e=>{data.examDate=e.target.value;save()};function updateCountdown(){if(!data.examDate){$('#countdown').textContent='Set a date';return}let n=Math.ceil((new Date(data.examDate+'T00:00:00')-Date.now())/864e5);$('#countdown').textContent=n>=0?n+' days':'Exam passed'}
let secs=1500,base=1500,run=false,timer;function draw(){let m=Math.floor(secs/60),s=secs%60;$('#timerDisplay').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}function stop(){clearInterval(timer);run=false;$('#startTimer').textContent='Start Focus'}$('#startTimer').onclick=()=>{if(run)return;run=true;$('#startTimer').textContent='Focusing...';timer=setInterval(()=>{secs--;draw();if(secs<=0){stop();data.totalMinutes+=base/60;data.xp+=25;updateStreak();save();toast('Session complete! +25 XP 🎉');secs=base;draw()}},1000)};$('#pauseTimer').onclick=stop;$('#resetTimer').onclick=()=>{stop();secs=base;draw()};document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{stop();base=secs=(+b.dataset.min)*60;document.querySelectorAll('.preset').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});
render();draw();
